# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: windows2019

variables:
  buildConfiguration: 'Release'
  projectPath: '**/*.csproj'

steps:
- task: DotNetCoreCLI@2
  name: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  name: 'Build'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
- task: DotNetCoreCLI@2
  name: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    
- task: ArchiveFiles@2
  name: 'ArchiveFile'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true

- task: AzureRmWebAppDeployment@4
  name: 'AppServiceDeploy'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription(e7359337-74f1-4ad3-91b2-302f52f2d6a8)'
    appType: 'webApp'
    WebAppName: 'multiserviceresolver'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop.zip'
    AppSettings: '-Author "Mirza Ghulam Rasyid"'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    TakeAppOfflineFlag: false